libs/shared/top-right-bar/src/lib/shared-top-right-bar.stories.tsx, libs/shared/top-right-bar/src/lib/shared-top-right-bar.tsx
I have fixed the `libs/shared/top-right-bar/src/lib/shared-top-right-bar.tsx` what should be do about the `libs/shared/top-menu-button` ?
=> fix(lib-shared-storybook-nested-components): [SKP-152] storybook-nested-components

apps/ppm/src/app/routes/private.ts, libs/data-access/adverts/src/lib/actions.ts, libs/data-access/adverts/src/lib/saga.ts, libs/features/adverts/src/lib/features-adverts.scss, libs/features/adverts/src/lib/features-adverts.tsx, libs/features/dashboard/mentor/src/lib/features-dashboard-mentor.tsx, libs/features/profile/src/lib/features-profile.scss, libs/features/profile/src/lib/features-profile.tsx
User profile page: http://localhost:4200/user
=> feat(user-profile-page)[skp-266]: Completed User Profile page

libs/data-access/user-profile/src/lib/saga.ts, libs/features/dashboard/mentor/src/lib/features-dashboard-mentor.tsx, libs/features/profile/src/lib/features-profile.tsx
- user profile feature fix saga
- import FeaturesDashboardMentor feature (this one shows only User adverts)
- remove social links linking (will be fixed with other task)
=> feat(user-profile-page)[skp-275]:  Fix user profile page

libs/features/authorization/src/lib/features-authorization.spec.tsx, libs/features/authorization/src/lib/features-authorization.tsx
Couldn't make useEffect to work in testing environment.
=> test(authorization): skp-332-features-authorization test for rendering

libs/features/dashboard/mentor/src/lib/features-dashboard-mentor.spec.tsx, libs/features/forgot-password/src/lib/features-forgot-password.spec.tsx, libs/features/lesson-page/src/lib/features-lesson-page.spec.tsx, libs/features/mentor/src/lib/features-mentor.spec.tsx, libs/features/mentors/src/lib/features-mentors.spec.tsx, libs/features/private-layout/src/lib/features-private-layout.spec.tsx, libs/features/private-layout/src/lib/features-private-layout.tsx, libs/features/registration/src/lib/features-registration.spec.tsx
Some tests are covering bare minimum of coverage. Some tests have typescript errors as I don't know how to mock history properly. All created tests passes.
=> test(features): SKP-334 Tests of features

libs/features/advert-page/src/lib/features-advert-page.tsx, libs/features/lesson-page/src/lib/features-lesson-page.tsx, libs/hooks/use-lesson/src/lib/hooks-use-lesson.tsx, libs/shared/lesson-component/src/lib/shared-lesson-component.tsx, libs/shared/lessons-accordion/src/lib/shared-lessons-accordion.tsx
Created main Edit Lesson functionality:
Created Edit Lesson button,
Created editLesson hook.
=> feat(feature-lesson shared-lesson):[SKP-388] create Edit Lesson feature

libs/data-access/mentors/src/lib/actions.ts, libs/data-access/mentors/src/lib/reducer.ts, libs/data-access/mentors/src/lib/saga.ts, libs/data-access/mentors/src/lib/types.ts
fixed saga functions
fixed reducer returned states
=> fix(mentors redux):[SKP-411] Fix types for Mentor interface

libs/data-access/adverts/src/lib/saga.ts
fixed logical error for redux result
=> fix(adverts redux):[SKP-413] Fix getAdvertById in Adverts Saga 

libs/data-access/lessons/src/lib/saga.ts
Problem solved for create/update lessons with no lessons image selected.
=> fix(lessons redux):[SKP-415] Fix imageUrl in Lessons Saga

libs/data-access/lessons/src/lib/saga.ts, libs/features/advert-page/src/lib/features-advert-page.tsx, libs/features/lesson-page/src/lib/features-lesson-page.tsx, libs/hooks/use-lesson/src/lib/hooks-use-lesson.tsx, libs/shared/lesson-component/src/lib/shared-lesson-component.tsx
autoclose drawer on success create/edit. 
fixed drawer cancel action
=> feat(lesson/drawer): [skp-416] autoclose drawer on success

apps/api/src/main.ts, libs/data-access/lessons/src/lib/saga.ts, libs/data-access/mentors/src/lib/selectors.ts, libs/features/lesson-page/src/lib/features-lesson-page.tsx, libs/shared/lesson-component/src/lib/shared-lesson-component.spec.tsx, libs/shared/lesson-component/src/lib/shared-lesson-component.stories.tsx, libs/shared/lesson-component/src/lib/shared-lesson-component.tsx, libs/shared/lessons-accordion/src/lib/shared-lessons-accordion.scss, libs/shared/lessons-accordion/src/lib/shared-lessons-accordion.spec.tsx, libs/shared/lessons-accordion/src/lib/shared-lessons-accordion.tsx, libs/shared/profile-form/src/lib/shared-profile-form.scss
Fixed errors of form fields and Required fields
=> fix(lesson):[SKP-390] Dev review. Fix drawer form fields

libs/features/advert-page/src/lib/features-advert-page.tsx, libs/shared/lesson-component/src/lib/shared-lesson-component.scss, libs/shared/lesson-component/src/lib/shared-lesson-component.tsx
Fixed drawer lesson form styles
=> fix(lesson dev-review):[SKP-390] Lesson shared component style fixes

libs/features/advert-page/src/lib/features-advert-page.tsx
added button Add Lesson after check of equality of profile and creator ids
=> fix(advert page):[SKP-390] Dev review. Add Lesson by Advert creator

libs/data-access/courses/src/lib/saga.ts
added snackbar messages on sign on to course
=> feat(add-student-to-course)[SKP-398]:Create redux saga function

libs/shared/create-course-form/src/lib/shared-create-course-form.scss, libs/shared/create-course-form/src/lib/shared-create-course-form.tsx
https://ppr-back-end-nest-js.atlassian.net/secure/RapidBoard.jspa?rapidView=3&projectKey=SKP&modal=detail&selectedIssue=SKP-436&assignee=5dbb0edad0d0d60c2e06b9f2
=> feat(shared-create-course-form): [skp-436] Fix add course form error messages

README.md
Added command for migrating mongo db up
=> Migrate mongo up

libs/shared/lessons-accordion/src/lib/shared-lessons-accordion.scss, libs/shared/lessons-accordion/src/lib/shared-lessons-accordion.tsx
Added icon for Add Lesson button
=> feat(shared/lesson-accordion):[SKP-438] Added icon for Add Lesson

libs/features/private-layout/src/lib/features-private-layout.scss, libs/shared/navigation/src/lib/shared-navigation.scss, libs/shared/navigation/src/lib/shared-navigation.tsx
Changes made in shared-navigation and features-private-layout.
=> feat(shared-navigation): [skp-439] Updated top menu bar style

libs/shared/login-component/src/lib/shared-login-component.tsx, libs/shared/registration/src/lib/shared-registration.scss, libs/shared/registration/src/lib/shared-registration.tsx
Changes made in shared-login-component and shared-registration
=> feat(shared-login-component): [skp-440] Fixed login and registration style

libs/shared/lessons-accordion/src/lib/shared-lessons-accordion.scss, libs/shared/lessons-accordion/src/lib/shared-lessons-accordion.tsx, libs/shared/navigation/src/lib/shared-navigation.scss, libs/shared/navigation/src/lib/shared-navigation.tsx
fixed lessons design and added z-index for menu
=> feat(shared-lessons-accordion): [skp-441] fixed lessons design and menu

libs/features/course-page/src/lib/features-course-page.tsx, libs/features/profile/src/lib/features-profile.tsx, libs/shared/courses-add-buttons/src/lib/shared-courses-add-buttons.tsx, libs/shared/create-course-form/src/lib/shared-create-course-form.scss, libs/shared/create-course-form/src/lib/shared-create-course-form.tsx, libs/shared/lesson-component/src/lib/shared-lesson-component.tsx, libs/shared/lessons-accordion/src/lib/shared-lessons-accordion.tsx, libs/shared/profile-form/src/lib/shared-profile-form.scss, libs/shared/profile-form/src/lib/shared-profile-form.tsx, libs/shared/user-profile-card/src/lib/shared-user-profile-card.tsx
https://pasteboard.co/K74awsj.png
=> fear(features-profile) : [skp-444] Changed drawer to dialog
